# 配队 莱卡恩 凯撒 苍角
allow_ultimate:
  - agent_name: "莱卡恩"

check_dodge_interval: 0.02
check_agent_interval: [0.4, 0.6]
check_special_attack_interval: [0.4, 0.6]
check_ultimate_interval: [0.4, 0.6]
check_chain_interval: [0.9, 1.1]
check_quick_interval: [0.9, 1.1]
auto_lock_interval: 5

# 连携技 上一个
t-chain-left: &t-chain-left
  - op_name: "按键-连携技-左"
  - op_name: "清除状态"
    state: "自定义-动作不打断"
  - op_name: "设置状态"
    state: "自定义-连携技换人"

# 连携技 下一个
t-chain-right: &t-chain-right
  - op_name: "按键-连携技-右"
  - op_name: "清除状态"
    state: "自定义-动作不打断"
  - op_name: "设置状态"
    state: "自定义-连携技换人"

# 招架支援-凯撒
t-dodge-caesar: &t-dodge-caesar
  - op_name: "设置状态"
    state: "自定义-凯撒-战意激昂"
  - op_name: "设置状态"
    state: "自定义-招架支援"
  - op_name: "切换角色"
    agent_name: "凯撒"

# 切换角色-凯撒
t-switch-caesar: &t-switch-caesar
  - op_name: "切换角色"
    agent_name: "凯撒"
  - op_name: "清除状态"
    state: "自定义-动作不打断"
  - op_name: "清除状态"
    state: "自定义-下场"
  - op_name: "等待秒数"
    seconds: 0.2

# 招架支援-苍角
t-dodge-soukaku: &t-dodge-soukaku
  - op_name: "设置状态"
    state: "自定义-招架支援"
  - op_name: "切换角色"
    agent_name: "苍角"

# 切换角色-苍角
t-switch-soukaku: &t-switch-soukaku
  - op_name: "切换角色"
    agent_name: "苍角"
  - op_name: "清除状态"
    state: "自定义-动作不打断"
  - op_name: "清除状态"
    state: "自定义-下场"
  - op_name: "等待秒数"
    seconds: 0.2

# 切换角色-莱卡恩
t-switch-lycaon: &t-switch-lycaon
  - op_name: "切换角色"
    agent_name: "莱卡恩"
  - op_name: "清除状态"
    state: "自定义-动作不打断"
  - op_name: "清除状态"
    state: "自定义-下场"
  - op_name: "等待秒数"
    seconds: 0.3

scenes:

  - triggers: [ "闪避识别-黄光", "闪避识别-红光", "闪避识别-声音" ]
    interval: 1
    handlers:
      # 部分连招霸体可以不闪避
      - states: "![自定义-动作不打断, 0, 30]"
        sub_states:
          - states: "[闪避识别-黄光]"
            sub_states:
              # 优先切凯撒进行上盾 核心持续时间30s
              - states: "([后台-1-凯撒] | [后台-2-凯撒]) & ![自定义-凯撒-战意激昂, 0, 30]"
                operations: *t-dodge-caesar

              # 其次切苍角上BUFF
              - states: "([后台-1-苍角] | [后台-2-苍角])"
                sub_states:
                  # 1命BUFF持续30s
                  - states: "![自定义-苍角-展旗, 0, 30]"
                    operations: *t-dodge-soukaku

                  # 连携技+1涡流 60能量发动特殊技 30能量+1涡流
                  # 平时准备着2个涡流 等招架或者连携时候可以直接展旗
#                  - states: "[苍角-涡流]{0,1}"
#                    operations: *t-dodge-soukaku

              # 默认凯撒带了原始朋克
              # 10S内没有招架支援 或者 回避支援 (原始朋克的BUFF) 就要切一次角色
              - states: "![自定义-招架支援, 0, 9]"
                sub_states:
                  # 如果苍角能量不足下次展旗 就优先切苍角
                  - states: "[苍角-涡流]{1, 2} & ( ([后台-1-苍角] & ![后台-1-能量]{60, 120}) | ([后台-2-苍角] & ![后台-2-能量]{60, 120}) )"
                    operations: *t-dodge-soukaku

                  # 其余情况切凯撒
                  - states: "[后台-1-凯撒] | [后台-2-凯撒]"
                    operations: *t-dodge-caesar

              # 其余情况闪避
              - states: ""
                operations:
                  - op_name: "设置状态"
                    state: "自定义-闪避"
                  - op_name: "按键-闪避"
                    post_delay: 0.1

          # 闪避
          - states: ""
            operations:
              - op_name: "设置状态"
                state: "自定义-闪避"
              - op_name: "按键-闪避"
                post_delay: 0.1

  - triggers: [ "按键可用-快速支援" ]
    interval: 1
    handlers:
      - states: "[按键可用-快速支援]"
        sub_states:
          # 苍角展旗 需要释放长按
          - states: "[前台-苍角]"
            operations:
              - op_name: "设置状态"
                state: "自定义-苍角-展旗"
              - op_name: "按键-快速支援"
              - op_name: "按键-普通攻击"
                way: "松开"
              - op_name: "按键-特殊攻击"
                way: "松开"
              - op_name: "设置状态"
                state: "自定义-快速支援换人"
              - op_name: "清除状态"
                state: "自定义-动作不打断"
          - states: ""
            operations:
              - op_name: "按键-快速支援"
              - op_name: "设置状态"
                state: "自定义-快速支援换人"

  - triggers: [ "按键可用-连携技" ]
    interval: 1
    handlers:
      - states: "[按键可用-连携技]"
        sub_states:
          - states: "[连携技-1-邦布]"
            operations: *t-chain-left
          - states: "[连携技-1-凯撒]"
            operations: *t-chain-left
          - states: "[连携技-2-凯撒]"
            operations: *t-chain-right
          - states: "[连携技-1-莱卡恩]"
            operations: *t-chain-left
          - states: "[连携技-2-莱卡恩]"
            operations: *t-chain-right
          - states: "[连携技-1-苍角]"
            operations: *t-chain-left
          - states: "[连携技-2-苍角]"
            operations: *t-chain-right

  - triggers: [ "前台-血量扣减" ]
    interval: 2
    handlers:
      - states: "[前台-血量扣减]{1, 100} & ![自定义-动作不打断, 0, 30]"
        operations:
          # 由于每个角色的僵直不一样 由具体角色控制如何处理
          - op_name: "设置状态"
            state: "自定义-血量扣减"

  - triggers: [ ]
    interval: 0.02
    handlers:
      - state_template: "站场模板-未识别角色"

      # 当前角色动作已经做完 可以切换角色了
      - states: "[自定义-下场]"
        sub_states:
          # 上凯撒盾
          - states: "![自定义-凯撒-战意激昂, 0, 30] & ( ([后台-1-凯撒] & [后台-1-能量]{40, 120}) | ([后台-2-凯撒] & [后台-2-能量]{40, 120}) )"
            operations: *t-switch-caesar

          # 上苍角buff
          - states: "![自定义-苍角-展旗, 0, 30] & ( [后台-1-苍角] | [后台-2-苍角] )"
            sub_states:
              - states: "[苍角-涡流]{3, 3}"
                operations: *t-switch-soukaku

              - states: "[苍角-涡流]{1, 2} & ( ([后台-1-苍角] & [后台-1-能量]{60, 120}) | ([后台-2-苍角] & [后台-2-能量]{60, 120}) )"
                operations: *t-switch-soukaku

              - states: "[苍角-涡流]{0, 0} & ( ([后台-1-苍角] & [后台-1-能量]{90, 120}) | ([后台-2-苍角] & [后台-2-能量]{90, 120}) )"
                operations: *t-switch-soukaku

          # 切回莱卡恩
          # 莱卡恩最后一段蓄力攻击会留在场上比较久 这里要等他下场后再切换
          - states: "![自定义-莱卡恩-普攻后摇, 0, 1.5]"
            operations: *t-switch-lycaon

      # 凯撒
      - states: "[前台-凯撒]"
        sub_states:
          - states: "[自定义-闪避]"
            operations:
              - op_name: "按键-普通攻击"
                post_delay: 0.1
                repeat: 15

          # 连携技出场会触发护盾
          - states: "[自定义-连携技换人]"
            operations:
              - op_name: "等待秒数"
                seconds: 2
              - op_name: "设置状态"
                state: "自定义-凯撒-战意激昂"

          - states: "[自定义-招架支援]"
            operations:
              - op_name: "按键-普通攻击"
                pre_delay: 0.1
                post_delay: 0.1
                repeat: 13

          # 有足够能量的话 就打一个特殊技能上盾再走
          # 有可能打出第一个盾击后 还不能切换到主C 这时候就不打第二个盾击浪费能量了
          - states: "[前台-能量]{40, 120} & ![自定义-凯撒-招架反击, 0, 3]"
            operations:
              - op_name: "设置状态"
                state: "自定义-动作不打断"
              - op_name: "按键-特殊攻击"
                post_delay: 0.1
                repeat: 7
              - op_name: "设置状态"
                state: "自定义-凯撒-战意激昂"
              - op_name: "设置状态"
                state: "自定义-凯撒-招架反击"
              - op_name: "设置状态"
                state: "自定义-下场"
              - op_name: "清除状态"
                state: "自定义-动作不打断"

          - states: ""
            operations:
              - op_name: "按键-普通攻击"
                post_delay: 0.2
              - op_name: "设置状态"
                state: "自定义-下场"

      # 苍角
      - states: "[前台-苍角]"
        sub_states:
          - states: "[自定义-闪避]"
            operations:
              - op_name: "按键-普通攻击"
                post_delay: 0.1
                repeat: 10

          # 连携技出场会触发展旗 判断涡流是否足够上buff
          - states: "[自定义-连携技换人, 0, 4]"
            sub_states:
              - states: "[苍角-涡流]{3, 3}"
                operations:
                  - op_name: "设置状态"
                    state: "自定义-苍角-展旗"
              - states: ""
                operations:
                  - op_name: "等待秒数"
                    seconds: 0.1

          # 招架出场
          - states: "[自定义-招架支援]"
            sub_states:
              # 如果涡流足够 就长按普攻接展旗
              - states: "![自定义-苍角-展旗, 0, 30] & [苍角-涡流]{3, 3}"
                operations:
                  - op_name: "设置状态"
                    state: "自定义-动作不打断"
                  - op_name: "按键-普通攻击"
                    way: "按下"
                    post_delay: 4
                  - op_name: "设置状态"
                    state: "自定义-下场"
                  - op_name: "清除状态"
                    state: "自定义-动作不打断"
              # 涡流不够的话 就要攻击一段时间到招架支援结束
              - states: ""
                operations:
                  - op_name: "设置状态"
                    state: "自定义-动作不打断"
                  - op_name: "按键-普通攻击"
                    post_delay: 0.1
                    repeat: 30
                  - op_name: "按键-闪避"
                    post_delay: 0.1
                  - op_name: "清除状态"
                    state: "自定义-动作不打断"

          # 涡流足够的话 直接展旗
          - states: "![自定义-苍角-展旗, 0, 25] & [苍角-涡流]{3, 3}"
            operations:
              - op_name: "设置状态"
                state: "自定义-动作不打断"
              - op_name: "按键-特殊攻击"
                way: "按下"
                post_delay: 4
              - op_name: "设置状态"
                state: "自定义-下场"
              - op_name: "清除状态"
                state: "自定义-动作不打断"
          # 普通情况下 如能能量足够补充涡流 就打强化特殊技
          - states: "![自定义-苍角-展旗, 0, 25] & [前台-能量]{60, 120} & [苍角-涡流]{2, 2}"
            operations:
              - op_name: "设置状态"
                state: "自定义-动作不打断"
              - op_name: "按键-特殊攻击"
                post_delay: 0.2
                repeat: 3
              - op_name: "按键-特殊攻击"
                way: "按下"
                post_delay: 4
              - op_name: "设置状态"
                state: "自定义-下场"
              - op_name: "清除状态"
                state: "自定义-动作不打断"
          # 普通情况下 如能能量足够补充涡流 就打强化特殊技
          - states: "![自定义-苍角-展旗, 0, 25] & [前台-能量]{60, 120} & [苍角-涡流]{1, 1}"
            operations:
              - op_name: "设置状态"
                state: "自定义-动作不打断"
              - op_name: "按键-特殊攻击"
                post_delay: 0.2
                repeat: 6
              - op_name: "按键-特殊攻击"
                way: "按下"
                post_delay: 4
              - op_name: "设置状态"
                state: "自定义-下场"
              - op_name: "清除状态"
                state: "自定义-动作不打断"
          # 普通情况下 如能能量足够补充涡流 就打强化特殊技
          - states: "![自定义-苍角-展旗, 0, 25] & [前台-能量]{90, 120} & [苍角-涡流]{0, 0}"
            operations:
              - op_name: "设置状态"
                state: "自定义-动作不打断"
              - op_name: "按键-特殊攻击"
                post_delay: 0.2
                repeat: 12
              - op_name: "按键-特殊攻击"
                way: "按下"
                post_delay: 4
              - op_name: "设置状态"
                state: "自定义-下场"
              - op_name: "清除状态"
                state: "自定义-动作不打断"
          # 剩余情况 可以直接下场
          - states: ""
            operations:
              - op_name: "按键-普通攻击"
                post_delay: 0.2
              - op_name: "设置状态"
                state: "自定义-下场"

      # 莱卡恩
      - states: "[前台-莱卡恩]"
        sub_states:
          - states: "[自定义-闪避]"
            operations:
              - op_name: "设置状态"
                state: "自定义-动作不打断"
              - op_name: "按键-普通攻击"
                post_delay: 0.1
                repeat: 3
              - op_name: "等待秒数"
                seconds: 0.6
              - op_name: "清除状态"
                state: "自定义-动作不打断"

          - states: "[自定义-快速支援换人]"
            operations:
              - op_name: "等待秒数"
                post_delay: 0.2

          - states: "[自定义-连携技换人]"
            operations:
              - op_name: "等待秒数"
                seconds: 2.5

          # 看看有没有buff需要上 注意刚切换上场的时候可能无法在做动作无法切人 稍微等一段时间
          - states: "![切换角色-莱卡恩]"
            sub_states:
              # 上凯撒盾
              - states: "![自定义-凯撒-战意激昂, 0, 30] & ( ([后台-1-凯撒] & [后台-1-能量]{40, 120}) | ([后台-2-凯撒] & [后台-2-能量]{40, 120}) )"
                operations: *t-switch-caesar

              # 上苍角buff
              - states: "![自定义-苍角-展旗, 0, 30] & ( [后台-1-苍角] | [后台-2-苍角] )"
                sub_states:
                  - states: "[苍角-涡流]{3, 3}"
                    operations: *t-switch-soukaku

                  - states: "[苍角-涡流]{1, 2} & ( ([后台-1-苍角] & [后台-1-能量]{60, 120}) | ([后台-2-苍角] & [后台-2-能量]{60, 120}) )"
                    operations: *t-switch-soukaku

                  - states: "[苍角-涡流]{0, 0} & ( ([后台-1-苍角] & [后台-1-能量]{90, 120}) | ([后台-2-苍角] & [后台-2-能量]{90, 120}) )"
                    operations: *t-switch-soukaku

          # 终结技 防止切换角色没切对 等一段时间再使用终结技
          - states: "![切换角色-莱卡恩] & [按键可用-终结技]"
            operations:
              - op_name: "设置状态"
                state: "自定义-动作不打断"
              - op_name: "按键-终结技"
                post_delay: 0.1
                repeat: 10
              - op_name: "等待秒数"
                seconds: 3.6
              - op_name: "清除状态"
                state: "自定义-动作不打断"

          # 强化特殊技 刚出场时候容易打不出来 先等等
          - states: "[前台-能量]{60, 120} & ![切换角色-莱卡恩]"
            operations:
              - op_name: "设置状态"
                state: "自定义-动作不打断"
              - op_name: "按键-特殊攻击"
                way: "按下"
                press: 0.3
                post_delay: 0.2
              - op_name: "按键-特殊攻击"
                way: "按下"
                press: 0.3
                post_delay: 1.6
              - op_name: "清除状态"
                state: "自定义-动作不打断"

          - states: ""
            operations:
              - op_name: "按键-普通攻击"
                way: "按下"
                press: 0.3
                post_delay: 0.8
              - op_name: "按键-普通攻击"
                way: "按下"
                press: 0.3
                post_delay: 0.8
              - op_name: "按键-普通攻击"
                way: "按下"
                press: 0.6
                post_delay: 1.3
              - op_name: "设置状态"
                state: "自定义-莱卡恩-普攻后摇"
